spring:
  main:
    web-application-type: reactive # gateway doesn't support spring
  application.name: gateway-service
  config.import: configserver:http://localhost:8080
  cloud.config:
    fail-fast: true
    username: dev
    password: dev