eureka:
  client.service-url.defaultZone: http://localhost:8081/eureka/ # must be defaultZone, not default-zone
  instance.prefer-ip-address: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  zipkin.baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1.0