eureka:
  client.service-url.defaultZone: ${DISCOVERY_HOST:http://localhost:8081}/eureka/ # must be defaultZone, not default-zone
  instance.prefer-ip-address: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  zipkin.baseUrl: ${ZIPKIN_HOST:http://localhost:9411}/
  sleuth:
    sampler:
      probability: 1.0

feign:
  client:
    config:
      default:
        read-timeout: 5000
        connect-timeout: 5000

internal-services:
  gateway-service:
    name: gateway-service
    url: ${GATEWAY_HOST:http://localhost:8082}
  auth-service:
    name: auth-service
  todo-service:
    name: todo-service
  account-service:
    name: account-service

oauth2:
  access-token-uri: ${GATEWAY_HOST:http://localhost:8082}/auth/oauth/token
