eureka:
  client.service-url.defaultZone: ${DISCOVERY_HOST:http://localhost:8081}/eureka/ # must be defaultZone, not default-zone
  instance.prefer-ip-address: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
spring:
  zipkin.baseUrl: ${ZIPKIN_HOST:http://localhost:9411}/
  sleuth:
    enabled: true
    sampler:
      probability: 1.0
logging:
  logstash:
    server: ${LOGSTASH_HOST:localhost:5044}
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    com.example: INFO

feign:
  client:
    config:
      default:
        read-timeout: 5000
        connect-timeout: 5000
  circuitbreaker:
    enabled: true
hystrix.command.default.execution.isolation:
  strategy: SEMAPHORE # make SecurityContext, ThreadLocal are available in service calls
  thread.timeoutInMilliseconds: ${feign.client.config.default.read-timeout}

internal-services:
  auth-service:
    name: auth-service
    url: ${AUTH_HOST:http://localhost:8083}
  todo-service:
    name: todo-service
    url: ${TODO_HOST:http://localhost:8084}
  account-service:
    name: account-service
    url: ${ACCOUNT_HOST:http://localhost:8085}

oauth2:
  access-token-uri: ${AUTH_HOST:http://localhost:8083}/oauth/token

management:
  endpoints:
    metrics.enabled: true
    prometheus.enabled: true
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    export:
      prometheus.enabled: true
    tags.application: ${spring.application.name}
