server.port: 8083

oauth2:
  key-store:
    path: todo-forge.jks
    password: todo-forge-123456
    alias: todo-forge
  client:
    access-token-validity: 1200
    refresh-token-validity: 2592000
    clients:
      todo-forge:
        client-id: todo-forge
        client-secret: 123
        grant-types:
          - authorization_code
          - refresh_token
          - implicit
          - password
        scopes:
          - read
          - write
        redirect-uris:
          - https://oauthdebugger.com/debug
      account-service:
        client-id: account-service
        client-secret: 123
        grant-types:
          - client_credentials
        scopes:
          - read
        access-token-validity: 100
        refresh-token-validity: 0
      todo-service:
        client-id: todo-service
        client-secret: 123
        grant-types:
          - client_credentials
        scopes:
          - read
        access-token-validity: 100
        refresh-token-validity: 0
  internal-client-credentials:
    account-service:
      client-id: account-service
      client-secret: 123
    todo-service:
      client-id: todo-service
      client-secret: 123

spring:
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # acks: acknowledges about persisting event
      # 0: no wait for kafka response
      # 1: leader (master) write success, not wait for follower (slaves)
      # -1: wait for all leader(master) , and replication (slaves)
      acks: -1
      # number of retry times
      retries: 1
      properties:
        # persisting response exceeds
        # timeout 1000ms -> trigger retry
        request.timeout.ms: 1000
        # prevent duplicate send for retryable processing
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
