server.port: 8084
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/todo?createDatabaseIfNotExist=true
    username: root
    password: 'dev'
    hikari:
      pool-name: HikariPool
      autoCommit: false
      maximumPoolSize: 10
      minimumIdle: 5
      connectionTimeout: 30000
      idleTimeout: 30000
      maxLifetime: 1800000
      ## PreparedStatement configuration
      cache-prep-stmts: true
      prep-stmt-cache-size: 250
      prep-stmt-cache-sql-limit: 2048
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: 'true'
        format_sql: 'true'
    hibernate:
      ddl-auto: update
oauth2:
  internal-client-credentials:
    account-service:
      client-id: account-service
      client-secret: 123
