global:
  scrape_interval: 5s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'auth-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8083']
  - job_name: 'todo-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'todo-service:8084' ]
  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'account-service:8085' ]